import { boat } from '@/lib/boat-data'
import { siteConfig } from '@/lib/site-config'
import { whatsappLeadUrl } from '@/lib/contact'

export const seoIntentPages = [
  {
    slug: 'malibu-response-lx-a-venda',
    title: `${siteConfig.listingName} à venda: preço, motor e fotos reais`,
    description: `${siteConfig.listingName} à venda por ${boat.priceLabel}. Veja motor Indmar Monsoon 350 SS V8, ${boat.engineHours} h, Zero Off GPS, bimini, carreta e dados para validar a compra.`,
    h1: `${siteConfig.listingName} à venda com dados reais do anúncio`,
    intro: 'Uma página objetiva para quem busca exatamente o modelo Malibu Response LX e quer confirmar preço, ano, horas, motor, equipamentos e fotos antes de falar com o vendedor.',
    keywords: ['Malibu Response LX à venda', 'Malibu Response LX usada', 'comprar Malibu Response LX', 'Malibu Response LX 2013'],
    sections: [
      { heading: 'O que comparar primeiro', text: 'Preço, ano, horas de motor, motorização, transmissão, equipamentos e itens inclusos devem estar claros antes de qualquer avanço.' },
      { heading: 'Dados deste anúncio', text: `O anúncio informa ${boat.year}, ${boat.engineHours} horas, motor Indmar Monsoon 350 SS V8 350 HP, direct drive, Zero Off GPS, bimini e carreta galvanizada.` },
      { heading: 'Próximo passo seguro', text: 'Use o WhatsApp para solicitar vídeos complementares, documentação disponível, informações de manutenção e condições para avaliação.' },
    ],
  },
  {
    slug: 'lancha-direct-drive-esqui-aquatico',
    title: 'Lancha direct drive para esqui aquático: Malibu Response LX',
    description: `Entenda por que a ${siteConfig.listingName} direct drive com Zero Off GPS atende quem busca uma lancha esportiva para esqui aquático e wakeboard.`,
    h1: 'Lancha direct drive para esqui aquático e wakeboard',
    intro: 'Conteúdo técnico para quem procura uma lancha esportiva usada com eixo direto, controle de velocidade e motor V8.',
    keywords: ['lancha direct drive à venda', 'lancha para esqui aquático', 'barco de wakeboard', 'Zero Off GPS lancha'],
    sections: [
      { heading: 'Direct drive e resposta previsível', text: 'A configuração direct drive é procurada por esportistas por entregar resposta direta, distribuição equilibrada e comportamento previsível.' },
      { heading: 'Zero Off GPS', text: 'O Zero Off utiliza referência de GPS para ajudar a manter velocidade consistente, atributo importante em treinos e prática esportiva.' },
      { heading: 'Conjunto anunciado', text: `A embarcação combina V8 350 HP, ${boat.engineHours} horas informadas, bimini e carreta inclusa para facilitar a comparação técnica.` },
    ],
  },
  {
    slug: 'comprar-lancha-usada-premium',
    title: 'Comprar lancha usada premium: checklist de avaliação',
    description: `Checklist para comprar lancha usada premium com foco em preço, horas, motor, casco, fotos reais e itens inclusos usando a ${siteConfig.listingName} como referência.`,
    h1: 'Comprar lancha usada premium com menos risco e mais dados',
    intro: 'Guia para compradores que ainda estão comparando modelos, mas procuram uma lancha usada premium com ficha técnica clara e contato direto.',
    keywords: ['comprar lancha usada', 'lancha usada premium', 'barco usado premium', 'lancha V8 350 HP usada'],
    sections: [
      { heading: 'Comece por dados objetivos', text: `Preço publicado (${boat.priceLabel}), ano (${boat.year}), horas (${boat.engineHours} h), motor, transmissão e itens inclusos devem estar fáceis de encontrar.` },
      { heading: 'Compare imagem e descrição', text: 'Fotos de casco, painel, estofamento, motor e carreta ajudam a preparar perguntas melhores antes do contato.' },
      { heading: 'Valide antes de avançar', text: 'Peça documentação disponível, histórico de manutenção, vídeos atuais e condições para inspeção e teste.' },
    ],
  },
  {
    slug: 'indmar-monsoon-350-ss-v8',
    title: 'Indmar Monsoon 350 SS V8: motor da Malibu Response LX',
    description: 'Conheça os principais pontos do motor Indmar Monsoon 350 SS V8 de 350 HP presente na Malibu Response LX anunciada.',
    h1: 'Indmar Monsoon 350 SS V8 na Malibu Response LX',
    intro: 'Uma visão prática do conjunto mecânico para quem pesquisa motor, potência, aplicação e perguntas essenciais antes da compra.',
    keywords: ['Indmar Monsoon 350 SS', 'motor Malibu Response LX', 'lancha V8 350 HP', 'motor Indmar Malibu'],
    sections: [
      { heading: 'Potência e aplicação', text: 'O Monsoon 350 SS é um V8 de 350 HP aplicado a embarcações esportivas, com foco em força, resposta e uso recreativo de alto desempenho.' },
      { heading: 'O que perguntar', text: 'Horas, revisões, fluidos, sistema de arrefecimento, partida a frio, ruídos, vazamentos e registros de manutenção são pontos centrais.' },
      { heading: 'Dados deste anúncio', text: `A embarcação anuncia ${boat.engineHours} horas de motor e transmissão direct drive. Informações complementares podem ser solicitadas pelo WhatsApp.` },
    ],
  },
  {
    slug: 'zero-off-gps-como-funciona',
    title: 'Zero Off GPS: como funciona em uma lancha esportiva',
    description: 'Entenda o que é o Zero Off GPS, por que ele importa no esqui aquático e como avaliar esse recurso em uma lancha usada.',
    h1: 'Zero Off GPS em lanchas de esqui aquático',
    intro: 'Explicação objetiva para compradores que encontraram o termo Zero Off e querem entender seu valor em uma embarcação esportiva.',
    keywords: ['Zero Off GPS', 'controle de velocidade lancha', 'Zero Off esqui aquático', 'lancha com Zero Off'],
    sections: [
      { heading: 'Consistência de velocidade', text: 'O sistema usa GPS para auxiliar o controle de velocidade, reduzindo variações durante a condução esportiva.' },
      { heading: 'Por que isso importa', text: 'Para o esqui aquático, consistência melhora repetibilidade, conforto e qualidade do treino.' },
      { heading: 'Como validar', text: 'Solicite vídeo de funcionamento, teste dos comandos, leitura do painel e confirmação de que o sistema está operacional.' },
    ],
  },
  {
    slug: 'direct-drive-vs-v-drive',
    title: 'Direct drive vs V-drive: diferenças para esqui e wakeboard',
    description: 'Compare direct drive e V-drive em lanchas esportivas e entenda qual configuração tende a atender melhor esqui aquático ou wakeboard.',
    h1: 'Direct drive vs V-drive em lanchas esportivas',
    intro: 'Comparativo simples para quem está escolhendo uma embarcação esportiva e precisa entender como a transmissão influencia uso, espaço e comportamento.',
    keywords: ['direct drive vs V-drive', 'lancha direct drive', 'lancha V-drive', 'barco esqui aquático wakeboard'],
    sections: [
      { heading: 'Direct drive', text: 'O motor fica mais centralizado e a transmissão segue em linha, configuração tradicionalmente associada ao esqui aquático e a uma esteira mais limpa.' },
      { heading: 'V-drive', text: 'O conjunto mecânico fica mais à popa, liberando espaço interno e favorecendo distribuição de peso usada em muitas aplicações de wakeboard.' },
      { heading: 'Qual faz sentido', text: 'A escolha depende do esporte prioritário, perfil de uso, número de ocupantes, armazenamento e comportamento desejado na água.' },
    ],
  },
  {
    slug: 'malibu-response-lx-2013-ficha-tecnica',
    title: 'Malibu Response LX 2013: ficha técnica e itens do anúncio',
    description: `Ficha técnica da Malibu Response LX 2013 anunciada com motor V8 350 HP, direct drive, Zero Off GPS, ${boat.engineHours} horas, bimini e carreta.`,
    h1: 'Ficha técnica da Malibu Response LX 2013 anunciada',
    intro: 'Resumo técnico indexável para compradores que pesquisam ano, motor, potência, transmissão, horas e equipamentos da embarcação.',
    keywords: ['Malibu Response LX 2013 ficha técnica', 'Malibu Response LX especificações', 'Malibu Response LX 350 HP', 'Malibu Response LX Zero Off'],
    sections: [
      { heading: 'Conjunto mecânico', text: 'Motor Indmar Monsoon 350 SS V8 5.7L de 350 HP com transmissão direct drive.' },
      { heading: 'Dados de uso publicados', text: `Ano ${boat.year} e ${boat.engineHours} horas informadas no anúncio, sujeitos à validação presencial e documental.` },
      { heading: 'Equipamentos apresentados', text: 'Controle Zero Off GPS, toldo bimini e carreta rodoviária galvanizada.' },
    ],
  },
  {
    slug: 'lancha-com-carreta-inclusa',
    title: 'Lancha com carreta inclusa: o que avaliar antes da compra',
    description: 'Veja o que avaliar em uma lancha usada com carreta inclusa, incluindo estrutura, pneus, rolamentos, documentação, elétrica e uso em rampa.',
    h1: 'Lancha usada com carreta inclusa: checklist essencial',
    intro: 'A carreta agrega praticidade e valor, mas precisa ser avaliada separadamente da embarcação para evitar custos inesperados.',
    keywords: ['lancha com carreta inclusa', 'lancha usada com carreta', 'carreta galvanizada para lancha', 'comprar barco com carreta'],
    sections: [
      { heading: 'Estrutura e corrosão', text: 'Verifique chassi, soldas, galvanização, pontos de corrosão, guincho, cintas e roletes.' },
      { heading: 'Rodagem e segurança', text: 'Avalie pneus, estepe, cubos, rolamentos, freios quando aplicáveis, iluminação e engate.' },
      { heading: 'Neste anúncio', text: 'A Malibu Response LX anunciada informa carreta rodoviária galvanizada inclusa, cuja condição deve ser confirmada presencialmente.' },
    ],
  },
  {
    slug: 'quantas-horas-motor-lancha-usada',
    title: 'Horas de motor em lancha usada: como interpretar o horímetro',
    description: 'Entenda como avaliar horas de motor em uma lancha usada e por que manutenção, tipo de uso e inspeção pesam mais que o número isolado.',
    h1: 'Como interpretar as horas de motor de uma lancha usada',
    intro: 'O horímetro é importante, mas não deve ser analisado sozinho. Histórico de manutenção, frequência de uso e conservação mudam completamente a leitura.',
    keywords: ['horas de motor lancha usada', 'quantas horas motor barco', 'horímetro lancha', '940 horas lancha'],
    sections: [
      { heading: 'Número não conta toda a história', text: 'Uso frequente com manutenção correta pode ser melhor que longos períodos parado sem cuidados preventivos.' },
      { heading: 'O que confirmar', text: 'Solicite registros de revisão, verifique partida a frio, ruídos, fumaça, vazamentos, temperatura e sistema de arrefecimento.' },
      { heading: 'Dado deste anúncio', text: `O anúncio informa ${boat.engineHours} horas de motor. A leitura deve ser validada no painel e em inspeção técnica.` },
    ],
  },
  {
    slug: 'checklist-documentacao-lancha-usada',
    title: 'Documentação de lancha usada: checklist antes de comprar',
    description: 'Checklist de documentação, titularidade, débitos, identificação e contrato para reduzir riscos na compra de uma lancha usada.',
    h1: 'Checklist documental para comprar uma lancha usada',
    intro: 'Antes de qualquer pagamento, confirme identidade do vendedor, titularidade da embarcação e documentação disponível com apoio profissional quando necessário.',
    keywords: ['documentação lancha usada', 'como comprar lancha usada', 'transferência embarcação usada', 'checklist compra barco usado'],
    sections: [
      { heading: 'Titularidade e identificação', text: 'Confirme dados do proprietário, identificação da embarcação e correspondência entre documentos e características físicas.' },
      { heading: 'Pendências e contrato', text: 'Verifique débitos, restrições, responsabilidades, forma de pagamento e condições de entrega em contrato.' },
      { heading: 'Transparência deste site', text: 'O anúncio não presume documentação validada. Esses dados devem ser solicitados e conferidos diretamente com o vendedor.' },
    ],
  },
  {
    slug: 'malibu-response-lx-preco',
    title: `Malibu Response LX preço: anúncio por ${boat.priceLabel}`,
    description: `Veja o preço anunciado da Malibu Response LX ${boat.year}, os itens inclusos e os fatores que devem ser comparados antes de negociar uma lancha esportiva usada.`,
    h1: `Preço da Malibu Response LX ${boat.year} anunciada`,
    intro: `A embarcação está anunciada por ${boat.priceLabel}. O valor deve ser analisado junto com ano, horas, motor, equipamentos, carreta, conservação e documentação.`,
    keywords: ['Malibu Response LX preço', 'preço Malibu Response LX usada', 'Malibu Response LX 2013 valor', 'lancha Malibu usada'],
    sections: [
      { heading: 'Preço publicado', text: `O valor anunciado é ${boat.priceLabel}, com negociação tratada diretamente com o vendedor.` },
      { heading: 'O que está informado', text: `Ano ${boat.year}, ${boat.engineHours} horas, V8 350 HP, Zero Off GPS, bimini e carreta inclusa.` },
      { heading: 'Como comparar', text: 'Compare estado, manutenção, acessórios, documentação, custo de transporte e eventual necessidade de revisão.' },
    ],
  },
  {
    slug: 'malibu-response-lx-vs-nautique-ski-200',
    title: 'Malibu Response LX vs Nautique Ski 200: qual escolher?',
    description: 'Compare Malibu Response LX e Nautique Ski 200 em proposta esportiva, transmissão, esteira, tecnologia e critérios de compra no mercado de usados.',
    h1: 'Malibu Response LX vs Nautique Ski 200',
    intro: 'Um comparativo para quem pesquisa lanchas premium de esqui aquático e precisa organizar diferenças de proposta, uso e diligência antes de comprar.',
    keywords: ['Malibu Response LX vs Nautique Ski 200', 'Malibu ou Nautique', 'lancha de esqui aquático premium', 'Nautique Ski 200 usada'],
    sections: [
      { heading: 'Proposta esportiva', text: 'Os dois modelos pertencem ao universo de lanchas especializadas para esportes rebocados. A escolha deve considerar prioridade entre slalom, recreação, conforto a bordo e disponibilidade de suporte.' },
      { heading: 'O que comparar na prática', text: 'Ano, motorização, horas, transmissão, controle de velocidade, histórico de manutenção, conservação do casco, estofamento e disponibilidade de peças devem ser avaliados barco a barco.' },
      { heading: 'Quando a Response LX faz sentido', text: 'A Response LX tende a interessar quem procura direct drive, proposta esportiva objetiva e um conjunto anunciado com Zero Off GPS, motor V8, bimini e carreta inclusa.' },
    ],
  },
  {
    slug: 'malibu-response-lx-vs-mastercraft-prostar',
    title: 'Malibu Response LX vs MasterCraft ProStar: comparação de compra',
    description: 'Veja como comparar Malibu Response LX e MasterCraft ProStar considerando uso no slalom, motorização, manutenção, equipamentos e condição do usado.',
    h1: 'Malibu Response LX vs MasterCraft ProStar',
    intro: 'Comparativo de intenção comercial para compradores que avaliam duas referências de lanchas de esqui aquático no mercado de usados.',
    keywords: ['Malibu Response LX vs MasterCraft ProStar', 'Malibu ou MasterCraft', 'ProStar usada', 'melhor lancha para slalom'],
    sections: [
      { heading: 'Sem vencedor universal', text: 'Não existe escolha correta apenas pela marca. O melhor negócio depende da unidade disponível, do histórico, do estado mecânico e da adequação ao esporte prioritário.' },
      { heading: 'Critérios decisivos', text: 'Compare qualidade da esteira na velocidade utilizada, resposta do motor, ergonomia, espaço, manutenção, peças, eletrônica, carreta e custo total de regularização e transporte.' },
      { heading: 'Dados objetivos desta Malibu', text: `A unidade anunciada informa ano ${boat.year}, ${boat.engineHours} horas, motor Indmar Monsoon 350 SS V8 de 350 HP, direct drive e Zero Off GPS.` },
    ],
  },
  {
    slug: 'malibu-response-lx-vale-a-pena',
    title: 'Malibu Response LX vale a pena? Análise para comprar usada',
    description: 'Entenda para quem a Malibu Response LX vale a pena, quais pontos validar e como analisar preço, horas, motor e equipamentos antes da compra.',
    h1: 'Malibu Response LX vale a pena?',
    intro: 'A resposta depende do perfil de uso e da condição real da unidade. Este guia organiza os fatores que transformam uma boa especificação em uma compra segura.',
    keywords: ['Malibu Response LX vale a pena', 'comprar Malibu Response LX usada', 'Malibu Response LX opinião', 'lancha de esqui aquático usada'],
    sections: [
      { heading: 'Para quem tende a valer a pena', text: 'Faz mais sentido para quem valoriza direct drive, prática de esqui aquático, controle de velocidade e comportamento esportivo previsível.' },
      { heading: 'O que pode mudar a decisão', text: 'Estado do motor, sistema de arrefecimento, transmissão, casco, estofamento, eletrônica, carreta, documentação e histórico de manutenção podem alterar totalmente o custo-benefício.' },
      { heading: 'Como decidir com menos risco', text: `Use os dados publicados — ${boat.year}, ${boat.engineHours} horas, V8 350 HP e itens inclusos — como ponto de partida, nunca como substituto de inspeção, teste e validação documental.` },
    ],
  },
  {
    slug: 'quanto-custa-manter-malibu-response-lx',
    title: 'Quanto custa manter uma Malibu Response LX?',
    description: 'Veja quais despesas compõem o custo de manutenção de uma Malibu Response LX usada: revisão, combustível, guarda, carreta, documentação e prevenção.',
    h1: 'Quanto custa manter uma Malibu Response LX usada',
    intro: 'O custo anual varia conforme uso, região, guarda e condição mecânica. Mais útil que prometer um número único é separar as despesas que precisam entrar no orçamento.',
    keywords: ['quanto custa manter Malibu Response LX', 'manutenção Malibu Response LX', 'custo lancha esportiva usada', 'custo anual lancha'],
    sections: [
      { heading: 'Custos recorrentes', text: 'Considere combustível, marina ou guarda, limpeza, bateria, lubrificantes, filtros, conservação do estofamento, seguro quando contratado e manutenção da carreta.' },
      { heading: 'Custos por uso e prevenção', text: 'Horas navegadas, qualidade da água, rotina de lavagem, invernagem, revisões preventivas e substituição de componentes de desgaste influenciam fortemente o orçamento.' },
      { heading: 'Reserva de segurança', text: 'Em uma embarcação usada, mantenha uma reserva específica para inspeção inicial, revisão pós-compra e correções não identificadas no anúncio.' },
    ],
  },
  {
    slug: 'perguntas-frequentes-malibu-response-lx',
    title: 'Perguntas frequentes sobre Malibu Response LX usada',
    description: 'Respostas objetivas sobre horas de motor, Zero Off, direct drive, wakeboard, manutenção, documentação e compra de uma Malibu Response LX usada.',
    h1: 'Perguntas frequentes sobre a Malibu Response LX',
    intro: 'Uma central de respostas rápidas para dúvidas comuns de compradores antes do contato, da inspeção e da negociação.',
    keywords: ['perguntas Malibu Response LX', 'FAQ Malibu Response LX', 'dúvidas lancha usada', 'comprar Malibu usada'],
    sections: [
      { heading: '900 horas de motor é muito?', text: 'O número isolado não decide a compra. Histórico de manutenção, tipo de uso, partida a frio, temperatura, ruídos, vazamentos e inspeção técnica pesam mais que uma referência genérica.' },
      { heading: 'Direct drive serve para wakeboard?', text: 'Pode atender uso recreativo, mas a configuração é tradicionalmente associada ao esqui aquático. Quem prioriza ondas maiores e mais espaço costuma também comparar opções V-drive.' },
      { heading: 'O Zero Off vale a pena?', text: 'Para quem pratica esportes rebocados e busca repetibilidade de velocidade, é um equipamento relevante. O funcionamento deve ser demonstrado e testado antes da compra.' },
      { heading: 'O que pedir ao vendedor?', text: 'Solicite vídeos atuais, partida a frio, painel ligado, motor em funcionamento, casco, interior, carreta, documentos disponíveis, histórico informado e condições para inspeção.' },
      { heading: 'Como saber se o preço está adequado?', text: 'Compare ano, horas, motorização, tecnologia, conservação, acessórios, carreta, documentação, localização e despesas imediatas após a compra.' },
    ],
  },
  {
    slug: 'impeller-lancha-o-que-e-quando-trocar',
    title: 'Impeller de lancha: o que é, sinais e quando trocar',
    description: 'Entenda a função do impeller no arrefecimento do motor marítimo, sinais de desgaste e perguntas essenciais antes de comprar uma lancha usada.',
    h1: 'Impeller de lancha: função, desgaste e prevenção',
    intro: 'O impeller é um componente pequeno, mas crítico para o sistema de arrefecimento. Falhas podem elevar a temperatura do motor e gerar prejuízo muito maior que a manutenção preventiva.',
    keywords: ['impeller lancha', 'quando trocar impeller', 'arrefecimento motor marítimo', 'manutenção preventiva lancha'],
    sections: [
      { heading: 'Para que serve', text: 'O impeller ajuda a movimentar água pelo sistema de arrefecimento do motor marítimo, contribuindo para o controle de temperatura durante o funcionamento.' },
      { heading: 'Sinais de atenção', text: 'Superaquecimento, fluxo de água irregular, histórico desconhecido ou longos períodos sem uso justificam inspeção imediata do componente.' },
      { heading: 'Na compra de uma usada', text: 'Pergunte quando ocorreu a última substituição, se houve superaquecimento e se existem registros de revisão do sistema de arrefecimento.' },
    ],
  },
  {
    slug: 'gelcoat-casco-lancha-como-avaliar',
    title: 'Gelcoat do casco: como avaliar trincas, manchas e reparos',
    description: 'Aprenda a avaliar o gelcoat de uma lancha usada, identificar sinais de reparo e diferenciar desgaste cosmético de problemas que exigem inspeção técnica.',
    h1: 'Como avaliar o gelcoat do casco de uma lancha usada',
    intro: 'O gelcoat é a camada externa de acabamento e proteção do casco. Aparência, uniformidade e reparos anteriores ajudam a contar a história da embarcação.',
    keywords: ['gelcoat lancha', 'trinca gelcoat', 'casco fibra lancha usada', 'inspeção casco embarcação'],
    sections: [
      { heading: 'O que observar', text: 'Procure diferenças de tonalidade, microtrincas, bolhas, riscos profundos, áreas opacas e reparos com acabamento irregular.' },
      { heading: 'Cosmético ou estrutural', text: 'Nem toda marca superficial indica dano estrutural, mas trincas recorrentes, deformações ou reparos extensos merecem avaliação profissional.' },
      { heading: 'Registro fotográfico', text: 'Fotos em luz natural e inspeção presencial ajudam a comparar brilho, alinhamento e uniformidade do casco antes da negociação.' },
    ],
  },
  {
    slug: 'checklist-inspecao-pre-compra-lancha',
    title: 'Inspeção pré-compra de lancha: checklist completo',
    description: 'Checklist de inspeção pré-compra para motor, casco, transmissão, elétrica, estofamento, carreta, documentação e teste na água.',
    h1: 'Checklist completo de inspeção pré-compra de lancha',
    intro: 'Uma boa inspeção reduz decisões baseadas apenas em fotos e ajuda a transformar o anúncio em dados verificáveis antes do pagamento.',
    keywords: ['inspeção pré-compra lancha', 'checklist barco usado', 'avaliar lancha usada', 'vistoria embarcação usada'],
    sections: [
      { heading: 'Motor e transmissão', text: 'Verifique partida a frio, ruídos, fumaça, vazamentos, temperatura, marcha à frente e à ré, vibração e resposta sob carga.' },
      { heading: 'Casco, interior e elétrica', text: 'Inspecione gelcoat, fundo, hélice, eixo, leme, estofamento, painel, bateria, bombas, iluminação e acessórios instalados.' },
      { heading: 'Teste e documentação', text: 'Faça teste na água quando possível, confira identificação, titularidade, pendências e registre por escrito as condições negociadas.' },
    ],
  },
  {
    slug: 'partida-a-frio-lancha-usada',
    title: 'Partida a frio em lancha usada: por que pedir ao vendedor',
    description: 'Entenda por que a partida a frio revela informações importantes sobre bateria, combustível, ignição, ruídos e condição geral do motor.',
    h1: 'Por que a partida a frio importa na compra de uma lancha usada',
    intro: 'Um motor já aquecido pode esconder dificuldade de partida, ruídos iniciais ou falhas de alimentação. Por isso, a demonstração deve começar com o conjunto realmente frio.',
    keywords: ['partida a frio lancha', 'avaliar motor lancha usada', 'vídeo motor barco', 'inspeção motor marítimo'],
    sections: [
      { heading: 'O que ela revela', text: 'Tempo de partida, estabilidade da marcha lenta, ruídos, fumaça, funcionamento da bateria e resposta inicial do motor.' },
      { heading: 'Como solicitar', text: 'Peça vídeo contínuo mostrando motor frio, painel antes da partida, acionamento, funcionamento e leitura de temperatura.' },
      { heading: 'Limitação importante', text: 'Vídeo ajuda, mas não substitui inspeção presencial, diagnóstico técnico e teste sob carga na água.' },
    ],
  },
  {
    slug: 'zero-off-vs-perfectpass',
    title: 'Zero Off vs PerfectPass: diferenças no controle de velocidade',
    description: 'Compare Zero Off e PerfectPass em lanchas esportivas e entenda tecnologia, aplicação, consistência e cuidados ao avaliar uma embarcação usada.',
    h1: 'Zero Off vs PerfectPass em lanchas esportivas',
    intro: 'Os dois sistemas ajudam no controle de velocidade, mas usam abordagens e gerações tecnológicas diferentes. A condição e o funcionamento real importam mais que o nome isolado.',
    keywords: ['Zero Off vs PerfectPass', 'controle velocidade esqui aquático', 'PerfectPass lancha', 'Zero Off GPS'],
    sections: [
      { heading: 'Zero Off', text: 'Utiliza referência de GPS e é fortemente associado à repetibilidade de velocidade em aplicações esportivas modernas.' },
      { heading: 'PerfectPass', text: 'É uma família conhecida de sistemas de controle de velocidade, com versões e sensores diferentes conforme geração e instalação.' },
      { heading: 'Como comparar uma usada', text: 'Teste comandos, leitura de velocidade, estabilidade, integração com painel e disponibilidade de suporte e peças.' },
    ],
  },
  {
    slug: 'consumo-motor-v8-lancha-esportiva',
    title: 'Consumo de motor V8 em lancha esportiva: o que influencia',
    description: 'Entenda por que o consumo de uma lancha V8 varia com peso, velocidade, carga, hélice, esporte praticado, manutenção e condições da água.',
    h1: 'O que influencia o consumo de uma lancha esportiva V8',
    intro: 'Não existe um único número confiável para todas as situações. O consumo muda bastante conforme uso, configuração e estado mecânico.',
    keywords: ['consumo lancha V8', 'consumo Malibu Response LX', 'motor 350 HP consumo', 'combustível lancha esportiva'],
    sections: [
      { heading: 'Variáveis de uso', text: 'Velocidade, aceleração, carga, número de ocupantes, prática esportiva, vento, corrente e tempo em marcha lenta alteram o consumo.' },
      { heading: 'Condição mecânica', text: 'Hélice inadequada, filtros, ignição, combustível, compressão e manutenção deficiente podem aumentar consumo e reduzir desempenho.' },
      { heading: 'Como estimar melhor', text: 'Use histórico real de abastecimento, horas navegadas e perfil de uso semelhante ao seu, evitando estimativas genéricas sem contexto.' },
    ],
  },
  {
    slug: 'helice-lancha-esportiva-como-avaliar',
    title: 'Hélice de lancha esportiva: como avaliar antes de comprar',
    description: 'Veja como inspecionar hélice, eixo, vibração, impactos, passo e sinais de reparo em uma lancha esportiva usada.',
    h1: 'Como avaliar a hélice de uma lancha esportiva usada',
    intro: 'A hélice influencia arrancada, rotação, eficiência e vibração. Pequenos danos podem comprometer desempenho e indicar impacto anterior.',
    keywords: ['hélice lancha esportiva', 'avaliar hélice barco usado', 'vibração lancha', 'eixo direct drive'],
    sections: [
      { heading: 'Inspeção visual', text: 'Procure pás amassadas, bordas irregulares, marcas de impacto, corrosão, soldas e diferenças de acabamento.' },
      { heading: 'Teste em funcionamento', text: 'Vibração, ruído, perda de desempenho ou rotação fora do esperado podem indicar hélice, eixo, alinhamento ou transmissão.' },
      { heading: 'Perguntas ao vendedor', text: 'Confirme reparos anteriores, troca de hélice, impactos, encalhes e disponibilidade de peça reserva.' },
    ],
  },
  {
    slug: 'arrefecimento-motor-maritimio-checklist',
    title: 'Sistema de arrefecimento de motor marítimo: checklist',
    description: 'Checklist para avaliar fluxo de água, impeller, mangueiras, temperatura, corrosão e histórico de superaquecimento em motor de lancha.',
    h1: 'Checklist do sistema de arrefecimento de uma lancha usada',
    intro: 'O sistema de arrefecimento merece atenção especial porque superaquecimento pode gerar danos caros e nem sempre aparece em fotos do anúncio.',
    keywords: ['arrefecimento motor marítimo', 'impeller motor lancha', 'superaquecimento lancha', 'revisão motor inboard'],
    sections: [
      { heading: 'Componentes principais', text: 'Impeller, bomba, mangueiras, abraçadeiras, entradas de água, termostato e trocadores quando aplicáveis devem ser inspecionados.' },
      { heading: 'Sinais de problema', text: 'Temperatura elevada, odor, vazamento, mangueiras ressecadas, fluxo irregular e histórico de superaquecimento exigem investigação.' },
      { heading: 'Validação em teste', text: 'Acompanhe temperatura desde a partida até o funcionamento sob carga e confirme estabilidade durante o teste na água.' },
    ],
  },
  {
    slug: 'manutencao-carreta-galvanizada-lancha',
    title: 'Manutenção de carreta galvanizada para lancha',
    description: 'Guia de manutenção para carreta galvanizada: lavagem, rolamentos, pneus, cubos, elétrica, guincho, cintas e corrosão.',
    h1: 'Como manter uma carreta galvanizada para lancha',
    intro: 'A galvanização ajuda contra corrosão, mas não elimina a necessidade de lavagem, inspeção e manutenção preventiva após uso em rampas e ambientes úmidos.',
    keywords: ['manutenção carreta galvanizada', 'carreta lancha rolamentos', 'lavar carreta barco', 'corrosão carreta lancha'],
    sections: [
      { heading: 'Após o uso', text: 'Lave estrutura, cubos, rodas, guincho e componentes expostos, especialmente após contato com água salobra ou salgada.' },
      { heading: 'Itens de segurança', text: 'Revise pneus, rolamentos, porcas, engate, correntes, iluminação, guincho, cintas e pontos de apoio do casco.' },
      { heading: 'Antes de viajar', text: 'Confirme aperto, calibragem, estepe, documentação e capacidade adequada ao peso transportado.' },
    ],
  },
  {
    slug: 'bimini-lancha-cuidados-e-avaliacao',
    title: 'Bimini de lancha: cuidados, conservação e avaliação',
    description: 'Saiba como avaliar tecido, estrutura, fixações e conservação de um bimini em uma lancha usada.',
    h1: 'Como avaliar e conservar o bimini de uma lancha',
    intro: 'O bimini melhora conforto ao sol, mas tecido, costuras e estrutura precisam estar íntegros para evitar manutenção imediata após a compra.',
    keywords: ['bimini lancha', 'toldo lancha manutenção', 'capota barco usada', 'acessórios Malibu Response LX'],
    sections: [
      { heading: 'Tecido e costuras', text: 'Verifique rasgos, desbotamento, mofo, ressecamento, costuras abertas e pontos de tensão.' },
      { heading: 'Estrutura e fixação', text: 'Cheque tubos, articulações, parafusos, bases, folgas e estabilidade durante abertura e fechamento.' },
      { heading: 'Conservação', text: 'Guarde seco, limpe com produtos adequados e evite navegar em velocidade incompatível com a estrutura aberta.' },
    ],
  },
  {
    slug: 'lancha-esqui-aquatico-vs-wakeboard',
    title: 'Lancha para esqui aquático vs wakeboard: diferenças',
    description: 'Entenda como casco, transmissão, distribuição de peso e esteira mudam entre lanchas voltadas a esqui aquático e wakeboard.',
    h1: 'Diferenças entre lancha de esqui aquático e de wakeboard',
    intro: 'A melhor embarcação depende do esporte prioritário. O que é desejável para uma esteira de slalom pode ser o oposto do que favorece uma onda maior para wakeboard.',
    keywords: ['lancha esqui aquático vs wakeboard', 'barco slalom', 'lancha wakeboard', 'direct drive esportes rebocados'],
    sections: [
      { heading: 'Esqui aquático', text: 'Busca resposta previsível, velocidade consistente e esteira mais limpa, especialmente em aplicações de slalom.' },
      { heading: 'Wakeboard', text: 'Tende a valorizar maior formação de onda, distribuição de peso e espaço interno para ocupantes e equipamentos.' },
      { heading: 'Escolha sem arrependimento', text: 'Defina esporte principal, frequência de uso, número de pessoas e tolerância a compromissos antes de comparar modelos.' },
    ],
  },
  {
    slug: 'vida-util-motor-lancha-usada',
    title: 'Vida útil de motor de lancha usada: o que realmente importa',
    description: 'Entenda por que horas, manutenção, uso, arrefecimento, combustível e períodos parado influenciam mais que uma regra fixa de vida útil.',
    h1: 'Como avaliar a vida útil de um motor de lancha usada',
    intro: 'Não existe uma quilometragem marítima universal. Dois motores com o mesmo horímetro podem ter condições completamente diferentes.',
    keywords: ['vida útil motor lancha', 'horas motor marítimo', 'motor lancha usada', 'durabilidade Indmar Monsoon'],
    sections: [
      { heading: 'Histórico pesa mais que idade', text: 'Revisões, qualidade de combustível, arrefecimento, frequência de uso e armazenamento influenciam diretamente a longevidade.' },
      { heading: 'Parado também desgasta', text: 'Longos períodos sem funcionamento podem afetar combustível, bateria, mangueiras, vedações e componentes internos.' },
      { heading: 'Como formar opinião', text: 'Combine horímetro, registros, inspeção, partida a frio, teste sob carga e diagnóstico por profissional qualificado.' },
    ],
  },
  {
    slug: 'custos-pos-compra-lancha-usada',
    title: 'Custos pós-compra de uma lancha usada: o que reservar',
    description: 'Planeje revisão inicial, transporte, documentação, seguro, guarda, carreta, combustível e correções após comprar uma lancha usada.',
    h1: 'Quais custos reservar depois de comprar uma lancha usada',
    intro: 'O preço do anúncio não representa sozinho o custo de entrada. Uma reserva pós-compra evita que pequenos ajustes interrompam o uso logo no início.',
    keywords: ['custos pós-compra lancha', 'quanto reservar barco usado', 'revisão inicial lancha', 'custo total compra embarcação'],
    sections: [
      { heading: 'Revisão inicial', text: 'Considere fluidos, filtros, bateria, impeller, correias, velas, mangueiras e itens encontrados na inspeção.' },
      { heading: 'Logística e regularização', text: 'Transporte, deslocamento, documentação, transferência, carreta e eventuais adequações podem alterar o custo total.' },
      { heading: 'Uso recorrente', text: 'Inclua combustível, guarda, limpeza, manutenção preventiva, seguro quando contratado e conservação da carreta.' },
    ],
  },
] as const

export type SeoIntentPage = (typeof seoIntentPages)[number]

export function getSeoIntentPage(slug: string) {
  return seoIntentPages.find((page) => page.slug === slug)
}

export function seoIntentPageUrl(slug: string) {
  return `${siteConfig.url}/guias/${slug}`
}

export const seoLeadHref = whatsappLeadUrl('primary')
